from typing import Tuple, Any

class DocObject:
    def stag(self, tag : str, href : str = None, rel : str = None): ...
    def asis(self, text : str): ...
    def getvalue(self) -> str: ...
    ...

class Doc:
    def ttl(self) -> Tuple[DocObject, Any, Text, Line]: ...
    ...

class Text:
    def __call__(self, p : str): ...
    ...

class Line:
    def __call__(self, tag : str, contents : str): ...
    ...

# class Tag:
#     def __call__(self, p : str, *kwargs : List[Any]) -> None: ...
#     def __init__(self, p : str) -> None: ...
#     def __enter__(self) -> None: ...
#     def __exit__(self): ...
