from typing import Any, Dict, List, Iterator, Union, Tuple

class Tensor:
    def __init__(self, arr : Any) -> None : ...
    def __getitem__(self, indices : Union[int, Tuple[Union[slice, int], ...]]) -> Any : ...
    def __iter__(self) -> Iterator[Any] : ...
    def __next__(self) -> Any: ...
    def cuda(self) -> 'Tensor': ...
    def view(self, *sizes : int) -> 'Tensor' : ...

class LongTensor(Tensor):
    ...
class FloatTensor(Tensor):
    def __init__(self, k : int, val : float) -> None : ...
    ...

def zeros(*sizes : int) -> Tensor : ...
