from torch import Tensor
from typing import Any, Union, Tuple

class Variable:
      def __init__(self, t : Tensor) -> None : ...
      def size(self) -> Tensor : ...
      def __getitem__(self, indices : Tuple[Union[slice, int], ...]) -> Any : ...
      ...
