
from typing import Union, Dict

NodeId = Union[int, str]
class Node:
    attr : Dict[str, str]
class AGraph:
    def __init__(self, directed : bool = False) -> None:
        ...
    def add_node(self, node_id : NodeId, **kwargs) -> None:
        ...
    def add_edge(self, node1_id : NodeId, node2_id : NodeId, **kwargs) -> None:
        ...
    def get_node(self, node_id : NodeId) -> Node:
        ...
    def draw(self, filename : str, **kwargs) -> None:
        ...
    ...
