
from torch import Tensor
from torch.autograd import Variable
from typing import Tuple

class GRU:
    def __init__(self, input_size : int, hidden_size : int) -> None : ...
    def __call__(self, input : Tensor, hidden : Tensor) \
        -> Tuple[Tensor, Tensor] : ...
    def cuda(self) -> 'GRU' : ...

class Embedding:
    def __init__(self, in_size : int, out_size : int) -> None : ...
    def __call__(self, input : Tensor) -> Tensor : ...
    def cuda(self) -> 'Embedding' : ...

class Linear:
    def __init__(self, hidden_size : int, output_size : int) -> None : ...
    def __call__(self, data : Tensor) -> Tensor : ...
    def cuda(self) -> 'Linear' : ...

class LogSoftmax:
    def __init__(self, dim : int) -> None : ...
    def __call__(self, data : Tensor) -> Tensor : ...
    def cuda(self) -> 'LogSoftmax' : ...

class Module:
    def cuda(self) -> 'Module': ...
    def __call__(self, *data : Variable) -> Tensor : ...
    ...

class Criterion: ...
class NLLLoss(Criterion): ...
