
from typing import Union, List, Any

Sexp = Union['SExpBase', List[Any]]

class SExpBase:
    ...
class Symbol(SExpBase):
    def __init__(self, name : str) -> None: ...
    ...

def loads(s : str) -> Sexp : ...
